twig:
    file_name_pattern: '*.twig'

    globals:
        video_id: '%video.id%'
        mapyApiKey: '%mapy_api_key%'
        globalVars: '@App\Controller\Twig\GlobalVariables'


when@test:
    twig:
        strict_variables: true
